services:
  - type: web
    name: frontend-service
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: backend-service
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
